config/routes.rb
Rails.application.routes.draw do
  resources :notes

  resources :pages
  resources :setups

  get 'setups/:id' => 'setups#show'
  get 'setups/filter/:pattern' => 'setups#filter'
  get 'setups/symbol/:symbol' => 'setups#symbol'
  get 'items' => 'items#index'

  root 'setups#index'

end

app/models/setup.rb
class Setup < ActiveRecord::Base
  belongs_to :item, :class_name => 'Item', :foreign_key => 'symbol', :primary_key => 'symbol'
  belongs_to :pattern_object, :class_name => 'Pattern', :foreign_key => 'pattern', :primary_key => 'name'

  def to_param
    "#{slug}"
  end

  def create_method(name, &block)
    self.class.send(:define_method, name, &block)
  end

  def create_attr(name)
    create_method("#{name}=".to_sym) { |val| instance_variable_set( "@" + name, val) }

    create_method(name.to_sym) { instance_variable_get( "@" + name ) }
  end
end

app/controllers/setups_controller.rb
class SetupsController < ApplicationController
  before_action :set_setup, only: [:edit, :update, :destroy]

  # GET /setups
  # GET /setups.json
  def index
    @setups = Setup.order('datetime desc, price asc, rating desc').paginate(:page => params[:page], :per_page => 10)
    @setups.each do |setup|
      Price.table_name = 'D_' + setup.symbol
      setup.create_attr('quotes')
      setup.quotes = Price.where('date <= ?', Time.at(setup.datetime - 1.day).to_datetime).order('date desc').first(100).reverse
      @setups << setup
    end
  end

  # GET /setups/filter/:pattern
  def filter
    @setups = Setup.where('pattern = ?', params[:pattern]).order(:datetime => 'desc').paginate(:page => params[:page], :per_page => 10)
    @setups.each do |setup|
      Price.table_name = 'D_' + setup.symbol
      setup.create_attr('quotes')
      setup.quotes = Price.where('date <= ?', Time.at(setup.datetime + 10.days).to_datetime).order('date desc').first(300).reverse
      @setups << setup
    end
  end

  # GET /setups/symbol/:symbol
  def symbol
    @setups = Setup.where('symbol = ?', params[:symbol]).order(:datetime => 'desc').paginate(:page => params[:page], :per_page => 10)
    @setups.each do |setup|
      Price.table_name = 'D_' + setup.symbol
      setup.create_attr('quotes')
      setup.quotes = Price.where('date <= ?', Time.at(setup.datetime + 10.days).to_datetime).order('date desc').first(300).reverse
      @setups << setup
    end
  end

  # GET /setups/1
  # GET /setups/1.json
  def show
    @setup = Setup.find_by_slug(params[:id]) or not_found
    Price.table_name = 'D_' + @setup.symbol
    @setup.create_attr('quotes')
    @setup.quotes = Price.order('date desc').all().reverse

    @other_days_setups = Setup.where('symbol =? and pattern =? and slug !=?', @setup.symbol, @setup.pattern, @setup.slug).order('datetime desc')
  end

  # GET /setups/new
  def new
    @setup = Setup.new
  end

  # GET /setups/1/edit
  def edit
  end

  # POST /setups
  # POST /setups.json
  def create
    @setup = Setup.new(setup_params)

    respond_to do |format|
      if @setup.save
        format.html { redirect_to @setup, notice: 'Setup was successfully created.' }
        format.json { render :show, status: :created, location: @setup }
      else
        format.html { render :new }
        format.json { render json: @setup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /setups/1
  # PATCH/PUT /setups/1.json
  def update
    respond_to do |format|
      if @setup.update(setup_params)
        format.html { redirect_to @setup, notice: 'Setup was successfully updated.' }
        format.json { render :show, status: :ok, location: @setup }
      else
        format.html { render :edit }
        format.json { render json: @setup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /setups/1
  # DELETE /setups/1.json
  def destroy
    @setup.destroy
    respond_to do |format|
      format.html { redirect_to setups_url, notice: 'Setup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setup
      @setup = Setup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setup_params
      params.require(:setup).permit(:name, :symbol, :datetime, :pattern)
    end
end

app/helpers/setups_helper.rb
module SetupsHelper
end

app/views/setups/_amchart.erb
<div id="chart_div_<%= setup.symbol%>_<%= setup.pattern_object.name%>_<%= setup.datetime.to_time.to_i%>" style="width:<%= width %>; height:<%= height %>;"></div>

<script type="text/javascript">
    var chart = AmCharts.makeChart( "chart_div_<%= setup.symbol%>_<%= setup.pattern_object.name%>_<%= setup.datetime.to_time.to_i%>", {
        "type": "serial",
        "theme": "light",
        "dataDateFormat":"YYYY-MM-DD",
        "valueAxes": [ {
            "position": "left"
        } ],
        "graphs": [ {
            "id": "g1",
            "balloonText": "Open:<b>[[open]]</b><br>Low:<b>[[low]]</b><br>High:<b>[[high]]</b><br>Close:<b>[[close]]</b><br>",
            "closeField": "close",
            "fillColors": "#7f8da9",
            "highField": "high",
            "lineColor": "#7f8da9",
            "lineAlpha": 1,
            "lowField": "low",
            "fillAlphas": 0.9,
            "negativeFillColors": "#db4c3c",
            "negativeLineColor": "#db4c3c",
            "openField": "open",
            "title": "Price:",
            "type": "candlestick",
            "valueField": "close"
        } ],
        "chartScrollbar": {
            "graph": "g1",
            "graphType": "line",
            "scrollbarHeight": 1
        },
        "chartCursor": {
            "valueLineEnabled": true,
            "valueLineBalloonEnabled": true
        },
        "categoryField": "date",
        "categoryAxis": {
            "parseDates": true
        },
        "stockEvents": [
            {
                "date": new Date( <%= setup.datetime.strftime('%Y') %>, <%= setup.datetime.strftime('%m') %>, <%= setup.datetime.strftime('%d') %> ),
                <% if setup.direction == 'BUY' %>
                "type": "arrowUp",
                "backgroundColor": "#00CC00",
                <% end %>
                <% if setup.direction == 'SELL' %>
                "type": "arrowDown",
                "backgroundColor": "#CC0000",
                <% end %>
                "graph": "g1",
                "description": "<%= setup.name %>"
            }
        ],
        "dataProvider": [
        <% setup.quotes.each do |day| %>
        {
            "date": "<%= day.date.to_s %>",
            "open": "<%= day.open.to_s %>",
            "high": "<%= day.high.to_s %>",
            "low": "<%= day.low.to_s %>",
            "close": "<%= day.close.to_s %>"
        },
        <% end %>
        ],
        "export": {
            "enabled": true,
            "position": "bottom-right"
        }
    } );
</script>

app/views/setups/_form.html.erb
<%= form_for(@setup) do |f| %>
  <% if @setup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setup.errors.count, "error") %> prohibited this setup from being saved:</h2>

      <ul>
      <% @setup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :symbol %><br>
    <%= f.text_field :symbol %>
  </div>
  <div class="field">
    <%= f.label :datetime %><br>
    <%= f.datetime_select :datetime %>
  </div>
  <div class="field">
    <%= f.label :pattern %><br>
    <%= f.text_field :pattern %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/setups/_highchart-light.erb
<div id="chart_div_<%= setup.symbol%>_<%= setup.pattern_object.name%>_<%= setup.datetime.to_time.to_i%>" style="width:<%= width %>; height:<%= height %>;"></div>

<script type="text/javascript">
    $(function () {
        // Add the background image to the container
        Highcharts.wrap(Highcharts.Chart.prototype, 'getContainer', function (proceed) {
            proceed.call(this);
            this.container.style.background = 'url(https://dl.dropboxusercontent.com/s/n7r1hokqxwwybz8/sand.png)';
        });
        Highcharts.theme = {
            colors: ["#f45b5b", "#8085e9", "#8d4654", "#7798BF", "#aaeeee", "#ff0066", "#eeaaee",
                "#55BF3B", "#DF5353", "#7798BF", "#aaeeee"],
            chart: {
                backgroundColor: null,
                style: {
                    fontFamily: "Signika, serif"
                }
            },
            title: {
                style: {
                    color: 'black',
                    fontSize: '16px',
                    fontWeight: 'bold'
                }
            },
            subtitle: {
                style: {
                    color: 'black'
                }
            },
            tooltip: {
                borderWidth: 0
            },
            legend: {
                itemStyle: {
                    fontWeight: 'bold',
                    fontSize: '13px'
                }
            },
            xAxis: {
                labels: {
                    style: {
                        color: '#6e6e70'
                    }
                }
            },
            yAxis: {
                labels: {
                    style: {
                        color: '#6e6e70'
                    }
                }
            },
            plotOptions: {
                series: {
                    shadow: true
                },
                candlestick: {
                    lineColor: '#404048'
                },
                map: {
                    shadow: false
                }
            },
            // Highstock specific
            navigator: {
                xAxis: {
                    gridLineColor: '#D0D0D8'
                }
            },
            rangeSelector: {
                buttonTheme: {
                    fill: 'white',
                    stroke: '#C0C0C8',
                    'stroke-width': 1,
                    states: {
                        select: {
                            fill: '#D0D0D8'
                        }
                    }
                }
            },
            scrollbar: {
                trackBorderColor: '#C0C0C8'
            },

            // General
            background2: '#E0E0E8'
        };
        // Apply the theme
        Highcharts.setOptions(Highcharts.theme);

        var data = [
            <% setup.quotes.each do |day| %>
            [<%= day.date.to_i %>000,<%= day.open %>,<%= day.hight %>,<%= day.low %>,<%= day.close %>],
            <% end %>
        ];
        // create the chart
        $('#chart_div_<%= setup.symbol%>_<%= setup.pattern_object.name%>_<%= setup.datetime.to_time.to_i%>').highcharts('StockChart', {
            rangeSelector : {
                selected : <%= selected %>
            },
            title : {
                text : ''
            },
            series : [{
                type : 'candlestick',
                id : '<%= setup.symbol%>_<%= setup.pattern_object.name%>_<%= setup.datetime.to_time.to_i%>',
                name : '<%= setup.name %>',
                data : data,
                dataGrouping : {
                    units : [
                        [
                            'week', // unit name
                            [1] // allowed multiples
                        ], [
                            'month',
                            [1, 2, 3, 4, 6]
                        ]
                    ]
                }
            }]
        });
    });
</script>

app/views/setups/_highchart.erb
<div id="chart_div_<%= setup.symbol%>_<%= setup.pattern_object.name%>_<%= setup.datetime.to_time.to_i%>" style="width:<%= width %>; height:<%= height %>;"></div>

<script type="text/javascript">
    $(function () {
        var data = [
            <% setup.quotes.each do |day| %>
            [<%= day.date.to_i %>000,<%= day.open %>,<%= day.high %>,<%= day.low %>,<%= day.close %>],
            <% end %>
        ];
        // create the chart
        $('#chart_div_<%= setup.symbol%>_<%= setup.pattern_object.name%>_<%= setup.datetime.to_time.to_i%>').highcharts('StockChart', {
            title: {
                text: '<%= setup.name%>'
            },
            subtitle: {
                text: '<%= setup.datetime.strftime('%B %d, %Y') %>'
            },
            xAxis: {
                gapGridLineWidth: 0
            },
            rangeSelector : {
                buttons : [{
                    type : 'day',
                    count : 1,
                    text : '1D'
                }, {
                    type : 'all',
                    count : 1,
                    text : 'All'
                }],
                selected : 1,
                inputEnabled : false
            },
            series : [{
                name : '<%=setup.name%>',
                type: 'area',
                data : data,
                gapSize: 5,
                tooltip: {
                    valueDecimals: 2
                },
                fillColor : {
                    linearGradient : {
                        x1: 0,
                        y1: 0,
                        x2: 0,
                        y2: 1
                    },
                    stops : [
                        [0, Highcharts.getOptions().colors[0]],
                        [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
                    ]
                },
                threshold: null
                // the event marker flags
                }, {
                type : 'flags',
                data : [
                    { x : Date.UTC(<%=setup.datetime.strftime('%Y').to_i%>, <%=setup.datetime.strftime('%m').to_i - 1%>, <%=setup.datetime.strftime('%d').to_i%>), title : 'Buy'},
                    <% others.each do |other| %>
                    { x : Date.UTC(<%=other.datetime.strftime('%Y').to_i%>, <%=other.datetime.strftime('%m').to_i - 1%>, <%=other.datetime.strftime('%d').to_i%>), title : 'Buy'},
                    <% end %>
                ]
            }]
        });
    });
</script>

app/views/setups/edit.html.erb
<h1>Editing Setup</h1>

<%= render 'form' %>

<%= link_to 'Show', @setup %> |
<%= link_to 'Back', setups_path %>

app/views/setups/filter.html.erb
<% content_for :title, 'Latest finance advices | Stock2.Watch' %>
<br>
<% @setups.each do |setup| %>
    <div class="page-header">
      <h1><a href="<%= setup_path setup %>" class="header-link"><%= setup.name %></a> <small><%= setup.datetime.strftime('%B %d, %Y') %></small></h1>
    </div>
    <table class="setup-table">
      <tr>
        <td class="align-top" width="50%">
          <table class="table table-border-bottom">
            <tr>
              <td>Symbol: <strong><%= setup.symbol %></strong></td><td>&nbsp;</td><td>Pattern: <strong><%= setup.pattern %></strong></td></td><td>&nbsp;</td><td>Exchange: <strong><%= setup.item.market %></strong></td>
            </tr>
            <% levels = JSON.parse setup.levels %>
            <% levels.each do |level| %>
                <% if level.has_key?('buy_stop') || level.has_key?('stop_loss') %>
                    <tr>
                      <% if level.has_key?('buy_stop')%><td>Buy Stop: <strong><%= level['buy_stop'].round(2) %></strong></td><td>&nbsp;</td><% end %><% if level.has_key?('stop_loss') %><td>Stop Loss: <strong><%= level['stop_loss'].round(2) %></strong></td><% end %><td>&nbsp;</td><td>&nbsp;</td>
                    </tr>
                <% end %>
                <% if level.has_key?('sell_stop') %>
                    <tr>
                      <td>Sell Stop: <strong><%= level['sell_stop'].round(2) %></strong></td><td>&nbsp;</td><td>Stop Loss: <strong><%= level['stop_loss'].round(2) %></strong></td><td>&nbsp;</td><td>&nbsp;</td>
                    </tr>
                <% end %>
            <% end %>
          </table>
          <h4 class="<%= setup.direction %>">
            <% if setup.direction == 'BUY_SELL' %>
                <span class="BUY">BUY</span> / <span class="SELL">SELL</span>
            <% else %>
                <%= setup.direction %>
            <% end %>
          </h4>
          <p>
            <strong><%= setup.pattern_object.name %></strong> - <%= truncate(setup.pattern_object.description, :length => 2000) %>
          </p>
        </td>
        <td class="left-border" width="50%">
          <%= render :partial => 'highchart', :locals => { :setup => setup, :width => '100%', :height => '550px', :selected => 0 } %>
        </td>
      </tr>
    </table>
<% end %>

<div class="paging">
  <%= will_paginate @setups, renderer: BootstrapPagination::Rails %>
</div>

app/views/setups/index.html.erb
<% content_for :title, 'Latest finance advices | Stock2.Watch' %>
<br>
  <% @setups.each do |setup| %>
    <div class="page-header">
      <h1><a href="<%= setup_path setup %>" class="header-link"><%= setup.name %></a> <small><%= setup.datetime.strftime('%B %d, %Y') %></small></h1>
    </div>
    <div>
      <table class="table">
        <tr>
          <td style="width:25%;">
            <p><strong><i>Advice</i></strong>&nbsp;<span class="<%= setup.direction %>"><%= setup.direction %></span></p>
              <% levels = JSON.parse setup.levels %>
              <% levels.each do |level| %>
                  <% if level.has_key?('buy_stop') %>
                    <p class="BUY">Buy Stop: <strong><%= level['buy_stop'].round(2) %></strong></p>
                    <p>Stop Loss: <strong><%= level['stop_loss'].round(2) %></strong></p>
                    <p>Take profit: <strong><%= level['take_profit'].round(2) %></strong></p>
                  <% end %>
                  <% if level.has_key?('sell_stop') %>
                    <p class="SELL">Sell Stop: <strong><%= level['sell_stop'].round(2) %></strong></p>
                    <p>Stop Loss: <strong><%= level['stop_loss'].round(2) %></strong></p>
                    <p>Take profit: <strong><%= level['take_profit'].round(2) %></strong></p>
                  <% end %>
              <% end %>
              <p>Date: <%= setup.datetime.strftime('%B %d, %Y') %></p>
          </td>
          <td style="width:35%;">
            <p><strong><i>Company Info</i></strong></p>
            <p>Symbol: <strong><%= setup.symbol %></strong></p>
            <p>Exchange: <strong><%= setup.item.market %></strong></p>
            <% unless setup.item.description.nil? %>
                <% desc = JSON.parse setup.item.description %>
                <% if desc.has_key?('Company_Info') %>
                    <% company = desc['Company_Info'] %>
                    <% if company.has_key?('CEO') %>
                        <p>CEO: <%= company['CEO'] %></p>
                    <% end %>
                    <% if company.has_key?('Industry') %>
                        <p>Industry: <%= company['Industry'] %></p>
                    <% end %>
                    <% if company.has_key?('Sector') %>
                        <p>Sector: <%= company['Sector'] %></p>
                    <% end %>
                    <% if company.has_key?('HQ_Location') %>
                        <p>HQ Location: <%= company['HQ_Location'] %></p>
                    <% end %>
                    <% if company.has_key?('Website') %>
                        <p>Website: <a href="<%= company['Website'] %>"><%= company['Website'] %></a></p>
                    <% end %>
                <% end %>
            <% end %>
          </td>
          <td style="width:40%;">
            <p><strong><i>Calculations</i></strong></p>
            <table class="table" id="mm_<%= setup.symbol%>_<%= setup.pattern_object.name%>_<%= setup.datetime.to_time.to_i%>">
              <tr><td>Account size <small>with overnight margin</small>: </td><td><input type="text" class="form-control total_money" placeholder="100000" onkeyup="calculate_total('mm_<%= setup.symbol%>_<%= setup.pattern_object.name%>_<%= setup.datetime.to_time.to_i%>', '<%= setup.direction %>', '<%= setup.levels %>')"></td></tr>
              <tr><td>Max risk %: </td><td><input type="text" class="form-control risk_percent" value="2"></td></tr>
              <tr><td style="border-bottom: 0px">Number of shares: </td><td style="border-bottom: 0px"><span class="shares">0</span></tr>
              <tr><td style="border-bottom: 0px">Profit: </td><td style="border-bottom: 0px"><span class="profit">0</span></tr>
              <tr><td style="border-bottom: 0px">Risk: </td><td style="border-bottom: 0px"><span class="risk">0</span></tr>
            </table>
          </td>
        </tr>
      </table>
    </div>
  <% end %>

<div class="paging">
  <%= will_paginate @setups, renderer: BootstrapPagination::Rails %>
</div>

app/views/setups/new.html.erb
<h1>New Setup</h1>

<%= render 'form' %>

<%= link_to 'Back', setups_path %>

app/views/setups/show.html.erb
<% content_for :title, @setup.name + ' ' + @setup.datetime.strftime('%B %d, %Y') + ' ' + @setup.direction + ' | Stock2.Watch' %>
<br>
<br>
<div>
  <%= render :partial => 'highchart', :locals => { :setup => @setup, :others => @other_days_setups, :width => '100%', :height => '500px', :selected => 1 } %>
</div>
<br>
<div>
  <table class="table">
    <tr>
      <td style="width:25%;">
        <p><strong><i>Advice</i></strong>&nbsp;<span class="<%= @setup.direction %>"><%= @setup.direction %></span></p>
        <% levels = JSON.parse @setup.levels %>
        <% levels.each do |level| %>
            <% if level.has_key?('buy_stop') %>
                <p class="BUY">Buy Stop: <strong><%= level['buy_stop'].round(2) %></strong></p>
                <p>Stop Loss: <strong><%= level['stop_loss'].round(2) %></strong></p>
                <p>Take profit: <strong><%= level['take_profit'].round(2) %></strong></p>
            <% end %>
            <% if level.has_key?('sell_stop') %>
                <p class="SELL">Sell Stop: <strong><%= level['sell_stop'].round(2) %></strong></p>
                <p>Stop Loss: <strong><%= level['stop_loss'].round(2) %></strong></p>
                <p>Take profit: <strong><%= level['take_profit'].round(2) %></strong></p>
            <% end %>
        <% end %>
        <p>Date: <%= @setup.datetime.strftime('%B %d, %Y') %></p>
      </td>
      <td style="width:35%;">
        <p><strong><i>Company Info</i></strong></p>
        <p>Symbol: <strong><%= @setup.symbol %></strong></p>
        <p>Exchange: <strong><%= @setup.item.market %></strong></p>
        <% unless @setup.item.description.nil? %>
            <% desc = JSON.parse @setup.item.description %>
            <% if desc.has_key?('Company_Info') %>
                <% company = desc['Company_Info'] %>
                <% if company.has_key?('CEO') %>
                    <p>CEO: <%= company['CEO'] %></p>
                <% end %>
                <% if company.has_key?('Industry') %>
                    <p>Industry: <%= company['Industry'] %></p>
                <% end %>
                <% if company.has_key?('Sector') %>
                    <p>Sector: <%= company['Sector'] %></p>
                <% end %>
                <% if company.has_key?('HQ_Location') %>
                    <p>HQ Location: <%= company['HQ_Location'] %></p>
                <% end %>
                <% if company.has_key?('Website') %>
                    <p>Website: <a href="<%= company['Website'] %>"><%= company['Website'] %></a></p>
                <% end %>
            <% end %>
        <% end %>
      </td>
      <td style="width:40%;">
        <p><strong><i>Calculations</i></strong></p>
        <table class="table" id="mm_<%= @setup.symbol%>_<%= @setup.pattern_object.name%>_<%= @setup.datetime.to_time.to_i%>">
          <tr><td>Account size <small>with overnight margin</small>: </td><td><input type="text" class="form-control total_money" placeholder="100000" onkeyup="calculate_total('mm_<%= @setup.symbol%>_<%= @setup.pattern_object.name%>_<%= @setup.datetime.to_time.to_i%>', '<%= @setup.direction %>', '<%= @setup.levels %>')"></td></tr>
          <tr><td>Max risk %: </td><td><input type="text" class="form-control risk_percent" value="2"></td></tr>
          <tr><td style="border-bottom: 0px">Number of shares: </td><td style="border-bottom: 0px"><span class="shares">0</span></tr>
          <tr><td style="border-bottom: 0px">Profit: </td><td style="border-bottom: 0px"><span class="profit">0</span></tr>
          <tr><td style="border-bottom: 0px">Risk: </td><td style="border-bottom: 0px"><span class="risk">0</span></tr>
        </table>
      </td>
    </tr>
  </table>
  <% @other_days_setups.each do |setup| %>
      <div class="page-header">
        <h1><a href="<%= setup_path setup %>" class="header-link"><%= setup.name %></a> <small><%= setup.datetime.strftime('%B %d, %Y') %></small></h1>
      </div>
      <div>
        <table class="table">
          <tr>
            <td style="width:100%;">
              <strong><i>Advice</i></strong>&nbsp;<span class="<%= setup.direction %>"><%= setup.direction %></span>
              <% levels = JSON.parse setup.levels %>
              <% levels.each do |level| %>
                  <% if level.has_key?('buy_stop') %>
                      <span class="BUY">Buy Stop: <strong><%= level['buy_stop'].round(2) %></strong></span>
                      <span>Stop Loss: <strong><%= level['stop_loss'].round(2) %></strong></span>
                      <span>Take profit: <strong><%= level['take_profit'].round(2) %></strong></span>
                  <% end %>
                  <% if level.has_key?('sell_stop') %>
                      <span class="SELL">Sell Stop: <strong><%= level['sell_stop'].round(2) %></strong></span>
                      <span>Stop Loss: <strong><%= level['stop_loss'].round(2) %></strong></span>
                      <span>Take profit: <strong><%= level['take_profit'].round(2) %></strong></span>
                  <% end %>
              <% end %>
            </td>
          </tr>
        </table>
      </div>
  <% end %>
</div>

app/views/setups/symbol.html.erb
<% content_for :title, 'Latest finance advices | Stock2.Watch' %>
<br>
<% @setups.each do |setup| %>
    <div class="page-header">
      <h1><a href="<%= setup_path setup %>" class="header-link"><%= setup.name %></a> <small><%= setup.datetime.strftime('%B %d, %Y') %></small></h1>
    </div>
    <table class="setup-table">
      <tr>
        <td class="align-top" width="50%">
          <table class="table table-border-bottom">
            <tr>
              <td>Symbol: <strong><%= setup.symbol %></strong></td><td>&nbsp;</td><td>Pattern: <strong><%= setup.pattern %></strong></td></td><td>&nbsp;</td><td>Exchange: <strong><%= setup.item.market %></strong></td>
            </tr>
            <% levels = JSON.parse setup.levels %>
            <% levels.each do |level| %>
                <% if level.has_key?('buy_stop') || level.has_key?('stop_loss') %>
                    <tr>
                      <% if level.has_key?('buy_stop')%><td>Buy Stop: <strong><%= level['buy_stop'].round(2) %></strong></td><td>&nbsp;</td><% end %><% if level.has_key?('stop_loss') %><td>Stop Loss: <strong><%= level['stop_loss'].round(2) %></strong></td><% end %><td>&nbsp;</td><td>&nbsp;</td>
                    </tr>
                <% end %>
                <% if level.has_key?('sell_stop') %>
                    <tr>
                      <td>Sell Stop: <strong><%= level['sell_stop'].round(2) %></strong></td><td>&nbsp;</td><td>Stop Loss: <strong><%= level['stop_loss'].round(2) %></strong></td><td>&nbsp;</td><td>&nbsp;</td>
                    </tr>
                <% end %>
            <% end %>
          </table>
          <h4 class="<%= setup.direction %>">
            <% if setup.direction == 'BUY_SELL' %>
                <span class="BUY">BUY</span> / <span class="SELL">SELL</span>
            <% else %>
                <%= setup.direction %>
            <% end %>
          </h4>
          <p>
            <strong><%= setup.pattern_object.name %></strong> - <%= truncate(setup.pattern_object.description, :length => 2000) %>
          </p>
        </td>
        <td class="left-border" width="50%">
          <%= render :partial => 'highchart', :locals => { :setup => setup, :width => '100%', :height => '550px', :selected => 0 } %>
        </td>
      </tr>
    </table>
<% end %>

<div class="paging">
  <%= will_paginate @setups, renderer: BootstrapPagination::Rails %>
</div>