config/routes.rb
Rails.application.routes.draw do
  resources :notes

  resources :pages
  resources :setups

  get 'setups/:id' => 'setups#show'
  get 'setups/filter/:pattern' => 'setups#filter'
  get 'setups/symbol/:symbol' => 'setups#symbol'
  get 'items' => 'items#index'

  root 'setups#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :setups, foreign_key: 'symbol', primary_key: 'symbol'

  def create_method(name, &block)
    self.class.send(:define_method, name, &block)
  end

  def create_attr(name)
    create_method("#{name}=".to_sym) { |val| instance_variable_set( "@" + name, val) }

    create_method(name.to_sym) { instance_variable_get( "@" + name ) }
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  # GET /items
  # GET /items.json
  def index
    @items = Item.all.paginate(:page => params[:page], :per_page => 50)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:symbol, :name)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :symbol %><br>
    <%= f.text_field :symbol %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_highchart.erb
<div id="chart_div_<%= item.symbol%>" style="width:<%= width %>; height:<%= height %>;"></div>

<script type="text/javascript">
    $(function () {
        var data = [
            <% item.quotes.each do |day| %>
            [<%= day.date.to_i %>000,<%= day.open %>,<%= day.hight %>,<%= day.low %>,<%= day.close %>],
            <% end %>
        ];
        var volume = [
            <% item.quotes.each do |day| %>
            [<%= day.date.to_i %>000,<%= day.volume %>],
            <% end %>
        ];
        // create the chart
        $('#chart_div_<%= item.symbol%>').highcharts('StockChart', {
            rangeSelector : {
                selected : <%= selected %>
            },
            title : {
                text : ''
            },
            yAxis: [{
                labels: {
                    align: 'right',
                    x: -3
                },
                title: {
                    text: 'OHLC'
                },
                height: '60%',
                lineWidth: 2
            }, {
                labels: {
                    align: 'right',
                    x: -3
                },
                title: {
                    text: 'Volume'
                },
                top: '65%',
                height: '35%',
                offset: 0,
                lineWidth: 2
            }],
            series : [{
                type : 'candlestick',
                id : '<%= item.symbol%>',
                name : '<%= item.name %>',
                data : data,
                dataGrouping : {
                    units : [
                        [
                            'week', // unit name
                            [1] // allowed multiples
                        ], [
                            'month',
                            [1, 2, 3, 4, 6]
                        ]
                    ]
                }
            }, {
                type: 'column',
                name: 'Volume',
                data: volume,
                yAxis: 1,
                dataGrouping: {
                    units : [
                        [
                            'week', // unit name
                            [1] // allowed multiples
                        ], [
                            'month',
                            [1, 2, 3, 4, 6]
                        ]
                    ]
                }
            }]
        });
    });
</script>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<% content_for :title, 'Financial Instruments | Stock2.Watch' %>
<br>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Symbol</th>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.symbol %></td>
        <td><%= item.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="paging">
    <%= will_paginate @items, renderer: BootstrapPagination::Rails %>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<% content_for :title, @item.name + ' | Stock2.Watch' %>
<div class="page-header">
  <h1><%= @item.name %></h1>
</div>
<br>
<table class="table table-show">
  <tr>
    <td>Symbol: <strong><%= @item.symbol %></strong></td><td>&nbsp;</td>
  </tr>
</table>
<div>
  <%= render :partial => 'highchart', :locals => { :item => @item, :width => '100%', :height => '650px', :selected => 1 } %>
</div>